spring:
  application:
    name: dmt-backend

  flyway:
    enabled: false

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: dmt
    password: dmt12345
    driver-class-name: oracle.jdbc.OracleDriver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect

jwt:
  secret: mySuperSecretKeyForDmtApplication123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789
  expiration: 86400000